# wrangler.toml
name = 'coderpath-react'
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

main = "./.vercel/output/functions/[[path]].js"

[pages]
# 这是 Pages 项目的构建输出目录。
# @cloudflare/next-on-pages 工具会将 Next.js 的构建产物转换为 Pages 兼容的格式，
# 并通常将其放置在 .vercel/output/static 目录下。
build_output_directory = ".vercel/output/static"