name = "coderpath-react"
main = ".open-next/worker.js"
compatibility_date = "2025-04-10"
compatibility_flags = [
  "nodejs_compat"
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
API_BASE_URL = "https://api.coderpath.dev" 